name = "DataAndPlotting"
uuid = "2209077a-c341-11e8-1342-0fe5c803cf1e"
authors = ["Erik Schnetter <schnetter@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
